name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Ensures a failure on one operating system doesn't cancel the other's test
      matrix:
        include:
          - os: ubuntu-latest
            script: ./install-linux.sh
            bin_path: /var/vanta/vanta-cli
          - os: macos-latest
            script: ./install-macos.sh
            bin_path: /usr/local/vanta/vanta-cli

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Test install
        run: |
          chmod +x ${{ matrix.script }}
          VANTA_SKIP_REGISTRATION_CHECK=1 VANTA_KEY=FAKEKEY VANTA_OWNER_EMAIL=fake-email@vanta.com VANTA_REGION=us ${{ matrix.script }}

      - name: Check that it's running correctly
        run: ${{ matrix.bin_path }} status
